var BFHStatesList = {
   'AD': {
     '02': 'Canillo',
     '03': 'Encamp',
     '04': 'La Massana',
     '05': 'Ordino',
     '06': 'Sant Julia de Loria',
     '07': 'Andorra la Vella',
     '08': 'Escaldes-Engordany'
   },
   'AE': {
     '01': 'Abu Dhabi',
     '02': 'Ajman',
     '03': 'Dubai',
     '04': 'Fujairah',
     '05': 'Ras Al Khaimah',
     '06': 'Sharjah',
     '07': 'Umm Al Quwain'
   },
   'AF': {
     '01': 'Badakhshan',
     '02': 'Badghis',
     '03': 'Baghlan',
     '05': 'Bamian',
     '06': 'Farah',
     '07': 'Faryab',
     '08': 'Ghazni',
     '09': 'Ghowr',
     '10': 'Helmand',
     '11': 'Herat',
     '13': 'Kabol',
     '14': 'Kapisa',
     '17': 'Lowgar',
     '18': 'Nangarhar',
     '19': 'Nimruz',
     '23': 'Kandahar',
     '24': 'Kondoz',
     '26': 'Takhar',
     '27': 'Vardak',
     '28': 'Zabol',
     '29': 'Paktika',
     '30': 'Balkh',
     '31': 'Jowzjan',
     '32': 'Samangan',
     '33': 'Sar-e Pol',
     '34': 'Konar',
     '35': 'Laghman',
     '36': 'Paktia',
     '37': 'Khowst',
     '38': 'Nurestan',
     '39': 'Oruzgan',
     '40': 'Parvan',
     '41': 'Daykondi',
     '42': 'Panjshir'
   },
   'AG': {
     '01': 'Barbuda',
     '03': 'Saint George',
     '04': 'Saint John',
     '05': 'Saint Mary',
     '06': 'Saint Paul',
     '07': 'Saint Peter',
     '08': 'Saint Philip',
     '09': 'Redonda'
   },
   'AL': {
     '40': 'Berat',
     '41': 'Diber',
     '42': 'Durres',
     '43': 'Elbasan',
     '44': 'Fier',
     '45': 'Gjirokaster',
     '46': 'Korce',
     '47': 'Kukes',
     '48': 'Lezhe',
     '49': 'Shkoder',
     '50': 'Tirane',
     '51': 'Vlore'
   },
   'AM': {
     '01': 'Aragatsotn',
     '02': 'Ararat',
     '03': 'Armavir',
     '04': 'Geghark\'unik\'',
     '05': 'Kotayk\'',
     '06': 'Lorri',
     '07': 'Shirak',
     '08': 'Syunik\'',
     '09': 'Tavush',
     '10': 'Vayots\' Dzor',
     '11': 'Yerevan'
   },
   'AO': {
     '01': 'Benguela',
     '02': 'Bie',
     '03': 'Cabinda',
     '04': 'Cuando Cubango',
     '05': 'Cuanza Norte',
     '06': 'Cuanza Sul',
     '07': 'Cunene',
     '08': 'Huambo',
     '09': 'Huila',
     '12': 'Malanje',
     '13': 'Namibe',
     '14': 'Moxico',
     '15': 'Uige',
     '16': 'Zaire',
     '17': 'Lunda Norte',
     '18': 'Lunda Sul',
     '19': 'Bengo',
     '20': 'Luanda'
   },
   'AR': {
     '01': 'Buenos Aires',
     '02': 'Catamarca',
     '03': 'Chaco',
     '04': 'Chubut',
     '05': 'Cordoba',
     '06': 'Corrientes',
     '07': 'Distrito Federal',
     '08': 'Entre Rios',
     '09': 'Formosa',
     '10': 'Jujuy',
     '11': 'La Pampa',
     '12': 'La Rioja',
     '13': 'Mendoza',
     '14': 'Misiones',
     '15': 'Neuquen',
     '16': 'Rio Negro',
     '17': 'Salta',
     '18': 'San Juan',
     '19': 'San Luis',
     '20': 'Santa Cruz',
     '21': 'Santa Fe',
     '22': 'Santiago del Estero',
     '23': 'Tierra del Fuego',
     '24': 'Tucuman'
   },
   'AT': {
     '01': 'Burgenland',
     '02': 'Karnten',
     '03': 'Niederosterreich',
     '04': 'Oberosterreich',
     '05': 'Salzburg',
     '06': 'Steiermark',
     '07': 'Tirol',
     '08': 'Vorarlberg',
     '09': 'Wien'
   },
   'AU': {
     '01': 'Australian Capital Territory',
     '02': 'New South Wales',
     '03': 'Northern Territory',
     '04': 'Queensland',
     '05': 'South Australia',
     '06': 'Tasmania',
     '07': 'Victoria',
     '08': 'Western Australia'
   },
   'AZ': {
     '01': 'Abseron',
     '02': 'Agcabadi',
     '03': 'Agdam',
     '04': 'Agdas',
     '05': 'Agstafa',
     '06': 'Agsu',
     '07': 'Ali Bayramli',
     '08': 'Astara',
     '09': 'Baki',
     '10': 'Balakan',
     '11': 'Barda',
     '12': 'Beylaqan',
     '13': 'Bilasuvar',
     '14': 'Cabrayil',
     '15': 'Calilabad',
     '16': 'Daskasan',
     '17': 'Davaci',
     '18': 'Fuzuli',
     '19': 'Gadabay',
     '20': 'Ganca',
     '21': 'Goranboy',
     '22': 'Goycay',
     '23': 'Haciqabul',
     '24': 'Imisli',
     '25': 'Ismayilli',
     '26': 'Kalbacar',
     '27': 'Kurdamir',
     '28': 'Lacin',
     '29': 'Lankaran',
     '30': 'Lankaran',
     '31': 'Lerik',
     '32': 'Masalli',
     '33': 'Mingacevir',
     '34': 'Naftalan',
     '35': 'Naxcivan',
     '36': 'Neftcala',
     '37': 'Oguz',
     '38': 'Qabala',
     '39': 'Qax',
     '40': 'Qazax',
     '41': 'Qobustan',
     '42': 'Quba',
     '43': 'Qubadli',
     '44': 'Qusar',
     '45': 'Saatli',
     '46': 'Sabirabad',
     '47': 'Saki',
     '48': 'Saki',
     '49': 'Salyan',
     '50': 'Samaxi',
     '51': 'Samkir',
     '52': 'Samux',
     '53': 'Siyazan',
     '54': 'Sumqayit',
     '55': 'Susa',
     '56': 'Susa',
     '57': 'Tartar',
     '58': 'Tovuz',
     '59': 'Ucar',
     '60': 'Xacmaz',
     '61': 'Xankandi',
     '62': 'Xanlar',
     '63': 'Xizi',
     '64': 'Xocali',
     '65': 'Xocavand',
     '66': 'Yardimli',
     '67': 'Yevlax',
     '68': 'Yevlax',
     '69': 'Zangilan',
     '70': 'Zaqatala',
     '71': 'Zardab'
   },
   'BA': {
     '01': 'Federation of Bosnia and Herzegovina',
     '02': 'Republika Srpska'
   },
   'BB': {
     '01': 'Christ Church',
     '02': 'Saint Andrew',
     '03': 'Saint George',
     '04': 'Saint James',
     '05': 'Saint John',
     '06': 'Saint Joseph',
     '07': 'Saint Lucy',
     '08': 'Saint Michael',
     '09': 'Saint Peter',
     '10': 'Saint Philip',
     '11': 'Saint Thomas'
   },
   'BD': {
     '81': 'Dhaka',
     '82': 'Khulna',
     '83': 'Rajshahi',
     '84': 'Chittagong',
     '85': 'Barisal',
     '86': 'Sylhet'
   },
   'BE': {
     '01': 'Antwerpen',
     '03': 'Hainaut',
     '04': 'Liege',
     '05': 'Limburg',
     '06': 'Luxembourg',
     '07': 'Namur',
     '08': 'Oost-Vlaanderen',
     '09': 'West-Vlaanderen',
     '10': 'Brabant Wallon',
     '11': 'Brussels Hoofdstedelijk Gewest',
     '12': 'Vlaams-Brabant',
     '13': 'Flanders',
     '14': 'Wallonia'
   },
   'BF': {
     '15': 'Bam',
     '19': 'Boulkiemde',
     '20': 'Ganzourgou',
     '21': 'Gnagna',
     '28': 'Kouritenga',
     '33': 'Oudalan',
     '34': 'Passore',
     '36': 'Sanguie',
     '40': 'Soum',
     '42': 'Tapoa',
     '44': 'Zoundweogo',
     '45': 'Bale',
     '46': 'Banwa',
     '47': 'Bazega',
     '48': 'Bougouriba',
     '49': 'Boulgou',
     '50': 'Gourma',
     '51': 'Houet',
     '52': 'Ioba',
     '53': 'Kadiogo',
     '54': 'Kenedougou',
     '55': 'Komoe',
     '56': 'Komondjari',
     '57': 'Kompienga',
     '58': 'Kossi',
     '59': 'Koulpelogo',
     '60': 'Kourweogo',
     '61': 'Leraba',
     '62': 'Loroum',
     '63': 'Mouhoun',
     '64': 'Namentenga',
     '65': 'Naouri',
     '66': 'Nayala',
     '67': 'Noumbiel',
     '68': 'Oubritenga',
     '69': 'Poni',
     '70': 'Sanmatenga',
     '71': 'Seno',
     '72': 'Sissili',
     '73': 'Sourou',
     '74': 'Tuy',
     '75': 'Yagha',
     '76': 'Yatenga',
     '77': 'Ziro',
     '78': 'Zondoma'
   },
   'BG': {
     '33': 'Mikhaylovgrad',
     '38': 'Blagoevgrad',
     '39': 'Burgas',
     '40': 'Dobrich',
     '41': 'Gabrovo',
     '42': 'Grad Sofiya',
     '43': 'Khaskovo',
     '44': 'Kurdzhali',
     '45': 'Kyustendil',
     '46': 'Lovech',
     '47': 'Montana',
     '48': 'Pazardzhik',
     '49': 'Pernik',
     '50': 'Pleven',
     '51': 'Plovdiv',
     '52': 'Razgrad',
     '53': 'Ruse',
     '54': 'Shumen',
     '55': 'Silistra',
     '56': 'Sliven',
     '57': 'Smolyan',
     '58': 'Sofiya',
     '59': 'Stara Zagora',
     '60': 'Turgovishte',
     '61': 'Varna',
     '62': 'Veliko Turnovo',
     '63': 'Vidin',
     '64': 'Vratsa',
     '65': 'Yambol'
   },
   'BH': {
     '01': 'Al Hadd',
     '02': 'Al Manamah',
     '05': 'Jidd Hafs',
     '06': 'Sitrah',
     '08': 'Al Mintaqah al Gharbiyah',
     '09': 'Mintaqat Juzur Hawar',
     '10': 'Al Mintaqah ash Shamaliyah',
     '11': 'Al Mintaqah al Wusta',
     '12': 'Madinat',
     '13': 'Ar Rifa',
     '14': 'Madinat Hamad',
     '15': 'Al Muharraq',
     '16': 'Al Asimah',
     '17': 'Al Janubiyah',
     '18': 'Ash Shamaliyah',
     '19': 'Al Wusta'
   },
   'BI': {
     '02': 'Bujumbura',
     '09': 'Bubanza',
     '10': 'Bururi',
     '11': 'Cankuzo',
     '12': 'Cibitoke',
     '13': 'Gitega',
     '14': 'Karuzi',
     '15': 'Kayanza',
     '16': 'Kirundo',
     '17': 'Makamba',
     '18': 'Muyinga',
     '19': 'Ngozi',
     '20': 'Rutana',
     '21': 'Ruyigi',
     '22': 'Muramvya',
     '23': 'Mwaro'
   },
   'BJ': {
     '07': 'Alibori',
     '08': 'Atakora',
     '09': 'Atlanyique',
     '10': 'Borgou',
     '11': 'Collines',
     '12': 'Kouffo',
     '13': 'Donga',
     '14': 'Littoral',
     '15': 'Mono',
     '16': 'Oueme',
     '17': 'Plateau',
     '18': 'Zou'
   },
   'BM': {
     '01': 'Devonshire',
     '02': 'Hamilton',
     '03': 'Hamilton',
     '04': 'Paget',
     '05': 'Pembroke',
     '06': 'Saint George',
     '07': 'Saint George\'s',
     '08': 'Sandys',
     '09': 'Smiths',
     '10': 'Southampton',
     '11': 'Warwick'
   },
   'BN': {
     '07': 'Alibori',
     '08': 'Belait',
     '09': 'Brunei and Muara',
     '10': 'Temburong',
     '11': 'Collines',
     '12': 'Kouffo',
     '13': 'Donga',
     '14': 'Littoral',
     '15': 'Tutong',
     '16': 'Oueme',
     '17': 'Plateau',
     '18': 'Zou'
   },
   'BO': {
     '01': 'Chuquisaca',
     '02': 'Cochabamba',
     '03': 'El Beni',
     '04': 'La Paz',
     '05': 'Oruro',
     '06': 'Pando',
     '07': 'Potosi',
     '08': 'Santa Cruz',
     '09': 'Tarija'
   },
   'BR': {
     '01': 'Acre',
     '02': 'Alagoas',
     '03': 'Amapa',
     '04': 'Amazonas',
     '05': 'Bahia',
     '06': 'Ceara',
     '07': 'Distrito Federal',
     '08': 'Espirito Santo',
     '11': 'Mato Grosso do Sul',
     '13': 'Maranhao',
     '14': 'Mato Grosso',
     '15': 'Minas Gerais',
     '16': 'Para',
     '17': 'Paraiba',
     '18': 'Parana',
     '20': 'Piaui',
     '21': 'Rio de Janeiro',
     '22': 'Rio Grande do Norte',
     '23': 'Rio Grande do Sul',
     '24': 'Rondonia',
     '25': 'Roraima',
     '26': 'Santa Catarina',
     '27': 'Sao Paulo',
     '28': 'Sergipe',
     '29': 'Goias',
     '30': 'Pernambuco',
     '31': 'Tocantins'
   },
   'BS': {
     '05': 'Bimini',
     '06': 'Cat Island',
     '10': 'Exuma',
     '13': 'Inagua',
     '15': 'Long Island',
     '16': 'Mayaguana',
     '18': 'Ragged Island',
     '22': 'Harbour Island',
     '23': 'New Providence',
     '24': 'Acklins and Crooked Islands',
     '25': 'Freeport',
     '26': 'Fresh Creek',
     '27': 'Governor\'s Harbour',
     '28': 'Green Turtle Cay',
     '29': 'High Rock',
     '30': 'Kemps Bay',
     '31': 'Marsh Harbour',
     '32': 'Nichollstown and Berry Islands',
     '33': 'Rock Sound',
     '34': 'Sandy Point',
     '35': 'San Salvador and Rum Cay'
   },
   'BT': {
     '05': 'Bumthang',
     '06': 'Chhukha',
     '07': 'Chirang',
     '08': 'Daga',
     '09': 'Geylegphug',
     '10': 'Ha',
     '11': 'Lhuntshi',
     '12': 'Mongar',
     '13': 'Paro',
     '14': 'Pemagatsel',
     '15': 'Punakha',
     '16': 'Samchi',
     '17': 'Samdrup',
     '18': 'Shemgang',
     '19': 'Tashigang',
     '20': 'Thimphu',
     '21': 'Tongsa',
     '22': 'Wangdi Phodrang'
   },
   'BW': {
     '01': 'Central',
     '03': 'Ghanzi',
     '04': 'Kgalagadi',
     '05': 'Kgatleng',
     '06': 'Kweneng',
     '08': 'North-East',
     '09': 'South-East',
     '10': 'Southern',
     '11': 'North-West'
   },
   'BY': {
     '01': 'Brestskaya Voblasts\'',
     '02': 'Homyel\'skaya Voblasts\'',
     '03': 'Hrodzyenskaya Voblasts\'',
     '04': 'Minsk',
     '05': 'Minskaya Voblasts\'',
     '06': 'Mahilyowskaya Voblasts\'',
     '07': 'Vitsyebskaya Voblasts\''
   },
   'BZ': {
     '01': 'Belize',
     '02': 'Cayo',
     '03': 'Corozal',
     '04': 'Orange Walk',
     '05': 'Stann Creek',
     '06': 'Toledo'
   },
   'CA': {
     'AB': 'Alberta',
     'BC': 'British Columbia',
     'MB': 'Manitoba',
     'NB': 'New Brunswick',
     'NL': 'Newfoundland',
     'NS': 'Nova Scotia',
     'NT': 'Northwest Territories',
     'NU': 'Nunavut',
     'ON': 'Ontario',
     'PE': 'Prince Edward Island',
     'QC': 'Quebec',
     'SK': 'Saskatchewan',
     'YT': 'Yukon Territory'
   },
   'CD': {
     '01': 'Bandundu',
     '02': 'Equateur',
     '04': 'Kasai-Oriental',
     '05': 'Katanga',
     '06': 'Kinshasa',
     '08': 'Bas-Congo',
     '09': 'Orientale',
     '10': 'Maniema',
     '11': 'Nord-Kivu',
     '12': 'Sud-Kivu'
   },
   'CF': {
     '01': 'Bamingui-Bangoran',
     '02': 'Basse-Kotto',
     '03': 'Haute-Kotto',
     '04': 'Mambere-Kadei',
     '05': 'Haut-Mbomou',
     '06': 'Kemo',
     '07': 'Lobaye',
     '08': 'Mbomou',
     '09': 'Nana-Mambere',
     '11': 'Ouaka',
     '12': 'Ouham',
     '13': 'Ouham-Pende',
     '14': 'Cuvette-Ouest',
     '15': 'Nana-Grebizi',
     '16': 'Sangha-Mbaere',
     '17': 'Ombella-Mpoko',
     '18': 'Bangui'
   },
   'CG': {
     '01': 'Bouenza',
     '04': 'Kouilou',
     '05': 'Lekoumou',
     '06': 'Likouala',
     '07': 'Niari',
     '08': 'Plateaux',
     '10': 'Sangha',
     '11': 'Pool',
     '12': 'Brazzaville',
     '13': 'Cuvette',
     '14': 'Cuvette-Ouest'
   },
   'CH': {
     '01': 'Aargau',
     '02': 'Ausser-Rhoden',
     '03': 'Basel-Landschaft',
     '04': 'Basel-Stadt',
     '05': 'Bern',
     '06': 'Fribourg',
     '07': 'Geneve',
     '08': 'Glarus',
     '09': 'Graubunden',
     '10': 'Inner-Rhoden',
     '11': 'Luzern',
     '12': 'Neuchatel',
     '13': 'Nidwalden',
     '14': 'Obwalden',
     '15': 'Sankt Gallen',
     '16': 'Schaffhausen',
     '17': 'Schwyz',
     '18': 'Solothurn',
     '19': 'Thurgau',
     '20': 'Ticino',
     '21': 'Uri',
     '22': 'Valais',
     '23': 'Vaud',
     '24': 'Zug',
     '25': 'Zurich',
     '26': 'Jura'
   },
   'CI': {
     '74': 'Agneby',
     '75': 'Bafing',
     '76': 'Bas-Sassandra',
     '77': 'Denguele',
     '78': 'Dix-Huit Montagnes',
     '79': 'Fromager',
     '80': 'Haut-Sassandra',
     '81': 'Lacs',
     '82': 'Lagunes',
     '83': 'Marahoue',
     '84': 'Moyen-Cavally',
     '85': 'Moyen-Comoe',
     '86': 'N\'zi-Comoe',
     '87': 'Savanes',
     '88': 'Sud-Bandama',
     '89': 'Sud-Comoe',
     '90': 'Vallee du Bandama',
     '91': 'Worodougou',
     '92': 'Zanzan'
   },
   'CL': {
     '01': 'Valparaiso',
     '02': 'Aisen del General Carlos Ibanez del Campo',
     '03': 'Antofagasta',
     '04': 'Araucania',
     '05': 'Atacama',
     '06': 'Bio-Bio',
     '07': 'Coquimbo',
     '08': 'Libertador General Bernardo O\'Higgins',
     '09': 'Los Lagos',
     '10': 'Magallanes y de la Antartica Chilena',
     '11': 'Maule',
     '12': 'Region Metropolitana',
     '13': 'Tarapaca',
     '14': 'Los Lagos',
     '15': 'Tarapaca',
     '16': 'Arica y Parinacota',
     '17': 'Los Rios'
   },
   'CM': {
     '04': 'Est',
     '05': 'Littoral',
     '07': 'Nord-Ouest',
     '08': 'Ouest',
     '09': 'Sud-Ouest',
     '10': 'Adamaoua',
     '11': 'Centre',
     '12': 'Extreme-Nord',
     '13': 'Nord',
     '14': 'Sud'
   },
   'CN': {
     '01': 'Anhui',
     '02': 'Zhejiang',
     '03': 'Jiangxi',
     '04': 'Jiangsu',
     '05': 'Jilin',
     '06': 'Qinghai',
     '07': 'Fujian',
     '08': 'Heilongjiang',
     '09': 'Henan',
     '10': 'Hebei',
     '11': 'Hunan',
     '12': 'Hubei',
     '13': 'Xinjiang',
     '14': 'Xizang',
     '15': 'Gansu',
     '16': 'Guangxi',
     '18': 'Guizhou',
     '19': 'Liaoning',
     '20': 'Nei Mongol',
     '21': 'Ningxia',
     '22': 'Beijing',
     '23': 'Shanghai',
     '24': 'Shanxi',
     '25': 'Shandong',
     '26': 'Shaanxi',
     '28': 'Tianjin',
     '29': 'Yunnan',
     '30': 'Guangdong',
     '31': 'Hainan',
     '32': 'Sichuan',
     '33': 'Chongqing'
   },
   'CO': {
     '01': 'Amazonas',
     '02': 'Antioquia',
     '03': 'Arauca',
     '04': 'Atlantico',
     '08': 'Caqueta',
     '09': 'Cauca',
     '10': 'Cesar',
     '11': 'Choco',
     '12': 'Cordoba',
     '14': 'Guaviare',
     '15': 'Guainia',
     '16': 'Huila',
     '17': 'La Guajira',
     '19': 'Meta',
     '20': 'Narino',
     '21': 'Norte de Santander',
     '22': 'Putumayo',
     '23': 'Quindio',
     '24': 'Risaralda',
     '25': 'San Andres y Providencia',
     '26': 'Santander',
     '27': 'Sucre',
     '28': 'Tolima',
     '29': 'Valle del Cauca',
     '30': 'Vaupes',
     '31': 'Vichada',
     '32': 'Casanare',
     '33': 'Cundinamarca',
     '34': 'Distrito Especial',
     '35': 'Bolivar',
     '36': 'Boyaca',
     '37': 'Caldas',
     '38': 'Magdalena'
   },
   'CR': {
     '01': 'Alajuela',
     '02': 'Cartago',
     '03': 'Guanacaste',
     '04': 'Heredia',
     '06': 'Limon',
     '07': 'Puntarenas',
     '08': 'San Jose'
   },
   'CU': {
     '01': 'Pinar del Rio',
     '02': 'Ciudad de la Habana',
     '03': 'Matanzas',
     '04': 'Isla de la Juventud',
     '05': 'Camaguey',
     '07': 'Ciego de Avila',
     '08': 'Cienfuegos',
     '09': 'Granma',
     '10': 'Guantanamo',
     '11': 'La Habana',
     '12': 'Holguin',
     '13': 'Las Tunas',
     '14': 'Sancti Spiritus',
     '15': 'Santiago de Cuba',
     '16': 'Villa Clara'
   },
   'CV': {
     '01': 'Boa Vista',
     '02': 'Brava',
     '04': 'Maio',
     '05': 'Paul',
     '07': 'Ribeira Grande',
     '08': 'Sal',
     '10': 'Sao Nicolau',
     '11': 'Sao Vicente',
     '13': 'Mosteiros',
     '14': 'Praia',
     '15': 'Santa Catarina',
     '16': 'Santa Cruz',
     '17': 'Sao Domingos',
     '18': 'Sao Filipe',
     '19': 'Sao Miguel',
     '20': 'Tarrafal'
   },
   'CY': {
     '01': 'Famagusta',
     '02': 'Kyrenia',
     '03': 'Larnaca',
     '04': 'Nicosia',
     '05': 'Limassol',
     '06': 'Paphos'
   },
   'CZ': {
     '52': 'Hlavni mesto Praha',
     '78': 'Jihomoravsky kraj',
     '79': 'Jihocesky kraj',
     '80': 'Vysocina',
     '81': 'Karlovarsky kraj',
     '82': 'Kralovehradecky kraj',
     '83': 'Liberecky kraj',
     '84': 'Olomoucky kraj',
     '85': 'Moravskoslezsky kraj',
     '86': 'Pardubicky kraj',
     '87': 'Plzensky kraj',
     '88': 'Stredocesky kraj',
     '89': 'Ustecky kraj',
     '90': 'Zlinsky kraj'
   },
   'DE': {
     '01': 'Baden-Wurttemberg',
     '02': 'Bayern',
     '03': 'Bremen',
     '04': 'Hamburg',
     '05': 'Hessen',
     '06': 'Niedersachsen',
     '07': 'Nordrhein-Westfalen',
     '08': 'Rheinland-Pfalz',
     '09': 'Saarland',
     '10': 'Schleswig-Holstein',
     '11': 'Brandenburg',
     '12': 'Mecklenburg-Vorpommern',
     '13': 'Sachsen',
     '14': 'Sachsen-Anhalt',
     '15': 'Thuringen',
     '16': 'Berlin'
   },
   'DJ': {
     '01': 'Ali Sabieh',
     '04': 'Obock',
     '05': 'Tadjoura',
     '06': 'Dikhil',
     '07': 'Djibouti',
     '08': 'Arta'
   },
   'DK': {
     '17': 'Hovedstaden',
     '18': 'Midtjylland',
     '19': 'Nordjylland',
     '20': 'Sjelland',
     '21': 'Syddanmark'
   },
   'DM': {
     '02': 'Saint Andrew',
     '03': 'Saint David',
     '04': 'Saint George',
     '05': 'Saint John',
     '06': 'Saint Joseph',
     '07': 'Saint Luke',
     '08': 'Saint Mark',
     '09': 'Saint Patrick',
     '10': 'Saint Paul',
     '11': 'Saint Peter'
   },
   'DO': {
     '01': 'Azua',
     '02': 'Baoruco',
     '03': 'Barahona',
     '04': 'Dajabon',
     '05': 'Distrito Nacional',
     '06': 'Duarte',
     '08': 'Espaillat',
     '09': 'Independencia',
     '10': 'La Altagracia',
     '11': 'Elias Pina',
     '12': 'La Romana',
     '14': 'Maria Trinidad Sanchez',
     '15': 'Monte Cristi',
     '16': 'Pedernales',
     '17': 'Peravia',
     '18': 'Puerto Plata',
     '19': 'Salcedo',
     '20': 'Samana',
     '21': 'Sanchez Ramirez',
     '23': 'San Juan',
     '24': 'San Pedro De Macoris',
     '25': 'Santiago',
     '26': 'Santiago Rodriguez',
     '27': 'Valverde',
     '28': 'El Seibo',
     '29': 'Hato Mayor',
     '30': 'La Vega',
     '31': 'Monsenor Nouel',
     '32': 'Monte Plata',
     '33': 'San Cristobal',
     '34': 'Distrito Nacional',
     '35': 'Peravia',
     '36': 'San Jose de Ocoa',
     '37': 'Santo Domingo'
   },
   'DZ': {
     '01': 'Alger',
     '03': 'Batna',
     '04': 'Constantine',
     '06': 'Medea',
     '07': 'Mostaganem',
     '09': 'Oran',
     '10': 'Saida',
     '12': 'Setif',
     '13': 'Tiaret',
     '14': 'Tizi Ouzou',
     '15': 'Tlemcen',
     '18': 'Bejaia',
     '19': 'Biskra',
     '20': 'Blida',
     '21': 'Bouira',
     '22': 'Djelfa',
     '23': 'Guelma',
     '24': 'Jijel',
     '25': 'Laghouat',
     '26': 'Mascara',
     '27': 'M\'sila',
     '29': 'Oum el Bouaghi',
     '30': 'Sidi Bel Abbes',
     '31': 'Skikda',
     '33': 'Tebessa',
     '34': 'Adrar',
     '35': 'Ain Defla',
     '36': 'Ain Temouchent',
     '37': 'Annaba',
     '38': 'Bechar',
     '39': 'Bordj Bou Arreridj',
     '40': 'Boumerdes',
     '41': 'Chlef',
     '42': 'El Bayadh',
     '43': 'El Oued',
     '44': 'El Tarf',
     '45': 'Ghardaia',
     '46': 'Illizi',
     '47': 'Khenchela',
     '48': 'Mila',
     '49': 'Naama',
     '50': 'Ouargla',
     '51': 'Relizane',
     '52': 'Souk Ahras',
     '53': 'Tamanghasset',
     '54': 'Tindouf',
     '55': 'Tipaza',
     '56': 'Tissemsilt'
   },
   'EC': {
     '01': 'Galapagos',
     '02': 'Azuay',
     '03': 'Bolivar',
     '04': 'Canar',
     '05': 'Carchi',
     '06': 'Chimborazo',
     '07': 'Cotopaxi',
     '08': 'El Oro',
     '09': 'Esmeraldas',
     '10': 'Guayas',
     '11': 'Imbabura',
     '12': 'Loja',
     '13': 'Los Rios',
     '14': 'Manabi',
     '15': 'Morona-Santiago',
     '17': 'Pastaza',
     '18': 'Pichincha',
     '19': 'Tungurahua',
     '20': 'Zamora-Chinchipe',
     '22': 'Sucumbios',
     '23': 'Napo',
     '24': 'Orellana'
   },
   'EE': {
     '01': 'Harjumaa',
     '02': 'Hiiumaa',
     '03': 'Ida-Virumaa',
     '04': 'Jarvamaa',
     '05': 'Jogevamaa',
     '06': 'Kohtla-Jarve',
     '07': 'Laanemaa',
     '08': 'Laane-Virumaa',
     '09': 'Narva',
     '10': 'Parnu',
     '11': 'Parnumaa',
     '12': 'Polvamaa',
     '13': 'Raplamaa',
     '14': 'Saaremaa',
     '15': 'Sillamae',
     '16': 'Tallinn',
     '17': 'Tartu',
     '18': 'Tartumaa',
     '19': 'Valgamaa',
     '20': 'Viljandimaa',
     '21': 'Vorumaa'
   },
   'EG': {
     '01': 'Ad Daqahliyah',
     '02': 'Al Bahr al Ahmar',
     '03': 'Al Buhayrah',
     '04': 'Al Fayyum',
     '05': 'Al Gharbiyah',
     '06': 'Al Iskandariyah',
     '07': 'Al Isma\'iliyah',
     '08': 'Al Jizah',
     '09': 'Al Minufiyah',
     '10': 'Al Minya',
     '11': 'Al Qahirah',
     '12': 'Al Qalyubiyah',
     '13': 'Al Wadi al Jadid',
     '14': 'Ash Sharqiyah',
     '15': 'As Suways',
     '16': 'Aswan',
     '17': 'Asyut',
     '18': 'Bani Suwayf',
     '19': 'Bur Sa\'id',
     '20': 'Dumyat',
     '21': 'Kafr ash Shaykh',
     '22': 'Matruh',
     '23': 'Qina',
     '24': 'Suhaj',
     '26': 'Janub Sina\'',
     '27': 'Shamal Sina\''
   },
   'ER': {
     '01': 'Anseba',
     '02': 'Debub',
     '03': 'Debubawi K\'eyih Bahri',
     '04': 'Gash Barka',
     '05': 'Ma\'akel',
     '06': 'Semenawi K\'eyih Bahri'
   },
   'ES': {
     '07': 'Islas Baleares',
     '27': 'La Rioja',
     '29': 'Madrid',
     '31': 'Murcia',
     '32': 'Navarra',
     '34': 'Asturias',
     '39': 'Cantabria',
     '51': 'Andalucia',
     '52': 'Aragon',
     '53': 'Canarias',
     '54': 'Castilla-La Mancha',
     '55': 'Castilla y Leon',
     '56': 'Catalonia',
     '57': 'Extremadura',
     '58': 'Galicia',
     '59': 'Pais Vasco',
     '60': 'Comunidad Valenciana'
   },
   'ET': {
     '44': 'Adis Abeba',
     '45': 'Afar',
     '46': 'Amara',
     '47': 'Binshangul Gumuz',
     '48': 'Dire Dawa',
     '49': 'Gambela Hizboch',
     '50': 'Hareri Hizb',
     '51': 'Oromiya',
     '52': 'Sumale',
     '53': 'Tigray',
     '54': 'YeDebub Biheroch Bihereseboch na Hizboch'
   },
   'FI': {
     '01': 'Aland',
     '06': 'Lapland',
     '08': 'Oulu',
     '13': 'Southern Finland',
     '14': 'Eastern Finland',
     '15': 'Western Finland'
   },
   'FJ': {
     '01': 'Central',
     '02': 'Eastern',
     '03': 'Northern',
     '04': 'Rotuma',
     '05': 'Western'
   },
   'FM': {
     '01': 'Kosrae',
     '02': 'Pohnpei',
     '03': 'Chuuk',
     '04': 'Yap'
   },
   'FR': {
     '97': 'Aquitaine',
     '98': 'Auvergne',
     '99': 'Basse-Normandie',
     'A1': 'Bourgogne',
     'A2': 'Bretagne',
     'A3': 'Centre',
     'A4': 'Champagne-Ardenne',
     'A5': 'Corse',
     'A6': 'Franche-Comte',
     'A7': 'Haute-Normandie',
     'A8': 'Ile-de-France',
     'A9': 'Languedoc-Roussillon',
     'B1': 'Limousin',
     'B2': 'Lorraine',
     'B3': 'Midi-Pyrenees',
     'B4': 'Nord-Pas-de-Calais',
     'B5': 'Pays de la Loire',
     'B6': 'Picardie',
     'B7': 'Poitou-Charentes',
     'B8': 'Provence-Alpes-Cote d\'Azur',
     'B9': 'Rhone-Alpes',
     'C1': 'Alsace'
   },
   'GA': {
     '01': 'Estuaire',
     '02': 'Haut-Ogooue',
     '03': 'Moyen-Ogooue',
     '04': 'Ngounie',
     '05': 'Nyanga',
     '06': 'Ogooue-Ivindo',
     '07': 'Ogooue-Lolo',
     '08': 'Ogooue-Maritime',
     '09': 'Woleu-Ntem'
   },
   'GB': {
     'A1': 'Barking and Dagenham',
     'A2': 'Barnet',
     'A3': 'Barnsley',
     'A4': 'Bath and North East Somerset',
     'A5': 'Bedfordshire',
     'A6': 'Bexley',
     'A7': 'Birmingham',
     'A8': 'Blackburn with Darwen',
     'A9': 'Blackpool',
     'B1': 'Bolton',
     'B2': 'Bournemouth',
     'B3': 'Bracknell Forest',
     'B4': 'Bradford',
     'B5': 'Brent',
     'B6': 'Brighton and Hove',
     'B7': 'Bristol, City of',
     'B8': 'Bromley',
     'B9': 'Buckinghamshire',
     'C1': 'Bury',
     'C2': 'Calderdale',
     'C3': 'Cambridgeshire',
     'C4': 'Camden',
     'C5': 'Cheshire',
     'C6': 'Cornwall',
     'C7': 'Coventry',
     'C8': 'Croydon',
     'C9': 'Cumbria',
     'D1': 'Darlington',
     'D2': 'Derby',
     'D3': 'Derbyshire',
     'D4': 'Devon',
     'D5': 'Doncaster',
     'D6': 'Dorset',
     'D7': 'Dudley',
     'D8': 'Durham',
     'D9': 'Ealing',
     'E1': 'East Riding of Yorkshire',
     'E2': 'East Sussex',
     'E3': 'Enfield',
     'E4': 'Essex',
     'E5': 'Gateshead',
     'E6': 'Gloucestershire',
     'E7': 'Greenwich',
     'E8': 'Hackney',
     'E9': 'Halton',
     'F1': 'Hammersmith and Fulham',
     'F2': 'Hampshire',
     'F3': 'Haringey',
     'F4': 'Harrow',
     'F5': 'Hartlepool',
     'F6': 'Havering',
     'F7': 'Herefordshire',
     'F8': 'Hertford',
     'F9': 'Hillingdon',
     'G1': 'Hounslow',
     'G2': 'Isle of Wight',
     'G3': 'Islington',
     'G4': 'Kensington and Chelsea',
     'G5': 'Kent',
     'G6': 'Kingston upon Hull, City of',
     'G7': 'Kingston upon Thames',
     'G8': 'Kirklees',
     'G9': 'Knowsley',
     'H1': 'Lambeth',
     'H2': 'Lancashire',
     'H3': 'Leeds',
     'H4': 'Leicester',
     'H5': 'Leicestershire',
     'H6': 'Lewisham',
     'H7': 'Lincolnshire',
     'H8': 'Liverpool',
     'H9': 'London, City of',
     'I1': 'Luton',
     'I2': 'Manchester',
     'I3': 'Medway',
     'I4': 'Merton',
     'I5': 'Middlesbrough',
     'I6': 'Milton Keynes',
     'I7': 'Newcastle upon Tyne',
     'I8': 'Newham',
     'I9': 'Norfolk',
     'J1': 'Northamptonshire',
     'J2': 'North East Lincolnshire',
     'J3': 'North Lincolnshire',
     'J4': 'North Somerset',
     'J5': 'North Tyneside',
     'J6': 'Northumberland',
     'J7': 'North Yorkshire',
     'J8': 'Nottingham',
     'J9': 'Nottinghamshire',
     'K1': 'Oldham',
     'K2': 'Oxfordshire',
     'K3': 'Peterborough',
     'K4': 'Plymouth',
     'K5': 'Poole',
     'K6': 'Portsmouth',
     'K7': 'Reading',
     'K8': 'Redbridge',
     'K9': 'Redcar and Cleveland',
     'L1': 'Richmond upon Thames',
     'L2': 'Rochdale',
     'L3': 'Rotherham',
     'L4': 'Rutland',
     'L5': 'Salford',
     'L6': 'Shropshire',
     'L7': 'Sandwell',
     'L8': 'Sefton',
     'L9': 'Sheffield',
     'M1': 'Slough',
     'M2': 'Solihull',
     'M3': 'Somerset',
     'M4': 'Southampton',
     'M5': 'Southend-on-Sea',
     'M6': 'South Gloucestershire',
     'M7': 'South Tyneside',
     'M8': 'Southwark',
     'M9': 'Staffordshire',
     'N1': 'St. Helens',
     'N2': 'Stockport',
     'N3': 'Stockton-on-Tees',
     'N4': 'Stoke-on-Trent',
     'N5': 'Suffolk',
     'N6': 'Sunderland',
     'N7': 'Surrey',
     'N8': 'Sutton',
     'N9': 'Swindon',
     'O1': 'Tameside',
     'O2': 'Telford and Wrekin',
     'O3': 'Thurrock',
     'O4': 'Torbay',
     'O5': 'Tower Hamlets',
     'O6': 'Trafford',
     'O7': 'Wakefield',
     'O8': 'Walsall',
     'O9': 'Waltham Forest',
     'P1': 'Wandsworth',
     'P2': 'Warrington',
     'P3': 'Warwickshire',
     'P4': 'West Berkshire',
     'P5': 'Westminster',
     'P6': 'West Sussex',
     'P7': 'Wigan',
     'P8': 'Wiltshire',
     'P9': 'Windsor and Maidenhead',
     'Q1': 'Wirral',
     'Q2': 'Wokingham',
     'Q3': 'Wolverhampton',
     'Q4': 'Worcestershire',
     'Q5': 'York',
     'Q6': 'Antrim',
     'Q7': 'Ards',
     'Q8': 'Armagh',
     'Q9': 'Ballymena',
     'R1': 'Ballymoney',
     'R2': 'Banbridge',
     'R3': 'Belfast',
     'R4': 'Carrickfergus',
     'R5': 'Castlereagh',
     'R6': 'Coleraine',
     'R7': 'Cookstown',
     'R8': 'Craigavon',
     'R9': 'Down',
     'S1': 'Dungannon',
     'S2': 'Fermanagh',
     'S3': 'Larne',
     'S4': 'Limavady',
     'S5': 'Lisburn',
     'S6': 'Derry',
     'S7': 'Magherafelt',
     'S8': 'Moyle',
     'S9': 'Newry and Mourne',
     'T1': 'Newtownabbey',
     'T2': 'North Down',
     'T3': 'Omagh',
     'T4': 'Strabane',
     'T5': 'Aberdeen City',
     'T6': 'Aberdeenshire',
     'T7': 'Angus',
     'T8': 'Argyll and Bute',
     'T9': 'Scottish Borders, The',
     'U1': 'Clackmannanshire',
     'U2': 'Dumfries and Galloway',
     'U3': 'Dundee City',
     'U4': 'East Ayrshire',
     'U5': 'East Dunbartonshire',
     'U6': 'East Lothian',
     'U7': 'East Renfrewshire',
     'U8': 'Edinburgh, City of',
     'U9': 'Falkirk',
     'V1': 'Fife',
     'V2': 'Glasgow City',
     'V3': 'Highland',
     'V4': 'Inverclyde',
     'V5': 'Midlothian',
     'V6': 'Moray',
     'V7': 'North Ayrshire',
     'V8': 'North Lanarkshire',
     'V9': 'Orkney',
     'W1': 'Perth and Kinross',
     'W2': 'Renfrewshire',
     'W3': 'Shetland Islands',
     'W4': 'South Ayrshire',
     'W5': 'South Lanarkshire',
     'W6': 'Stirling',
     'W7': 'West Dunbartonshire',
     'W8': 'Eilean Siar',
     'W9': 'West Lothian',
     'X1': 'Isle of Anglesey',
     'X2': 'Blaenau Gwent',
     'X3': 'Bridgend',
     'X4': 'Caerphilly',
     'X5': 'Cardiff',
     'X6': 'Ceredigion',
     'X7': 'Carmarthenshire',
     'X8': 'Conwy',
     'X9': 'Denbighshire',
     'Y1': 'Flintshire',
     'Y2': 'Gwynedd',
     'Y3': 'Merthyr Tydfil',
     'Y4': 'Monmouthshire',
     'Y5': 'Neath Port Talbot',
     'Y6': 'Newport',
     'Y7': 'Pembrokeshire',
     'Y8': 'Powys',
     'Y9': 'Rhondda Cynon Taff',
     'Z1': 'Swansea',
     'Z2': 'Torfaen',
     'Z3': 'Vale of Glamorgan, The',
     'Z4': 'Wrexham',
     'Z5': 'Bedfordshire',
     'Z6': 'Central Bedfordshire',
     'Z7': 'Cheshire East',
     'Z8': 'Cheshire West and Chester',
     'Z9': 'Isles of Scilly'
   },
   'GD': {
     '01': 'Saint Andrew',
     '02': 'Saint David',
     '03': 'Saint George',
     '04': 'Saint John',
     '05': 'Saint Mark',
     '06': 'Saint Patrick'
   },
   'GE': {
     '01': 'Abashis Raioni',
     '02': 'Abkhazia',
     '03': 'Adigenis Raioni',
     '04': 'Ajaria',
     '05': 'Akhalgoris Raioni',
     '06': 'Akhalk\'alak\'is Raioni',
     '07': 'Akhalts\'ikhis Raioni',
     '08': 'Akhmetis Raioni',
     '09': 'Ambrolauris Raioni',
     '10': 'Aspindzis Raioni',
     '11': 'Baghdat\'is Raioni',
     '12': 'Bolnisis Raioni',
     '13': 'Borjomis Raioni',
     '14': 'Chiat\'ura',
     '15': 'Ch\'khorotsqus Raioni',
     '16': 'Ch\'okhatauris Raioni',
     '17': 'Dedop\'listsqaros Raioni',
     '18': 'Dmanisis Raioni',
     '19': 'Dushet\'is Raioni',
     '20': 'Gardabanis Raioni',
     '21': 'Gori',
     '22': 'Goris Raioni',
     '23': 'Gurjaanis Raioni',
     '24': 'Javis Raioni',
     '25': 'K\'arelis Raioni',
     '26': 'Kaspis Raioni',
     '27': 'Kharagaulis Raioni',
     '28': 'Khashuris Raioni',
     '29': 'Khobis Raioni',
     '30': 'Khonis Raioni',
     '31': 'K\'ut\'aisi',
     '32': 'Lagodekhis Raioni',
     '33': 'Lanch\'khut\'is Raioni',
     '34': 'Lentekhis Raioni',
     '35': 'Marneulis Raioni',
     '36': 'Martvilis Raioni',
     '37': 'Mestiis Raioni',
     '38': 'Mts\'khet\'is Raioni',
     '39': 'Ninotsmindis Raioni',
     '40': 'Onis Raioni',
     '41': 'Ozurget\'is Raioni',
     '42': 'P\'ot\'i',
     '43': 'Qazbegis Raioni',
     '44': 'Qvarlis Raioni',
     '45': 'Rust\'avi',
     '46': 'Sach\'kheris Raioni',
     '47': 'Sagarejos Raioni',
     '48': 'Samtrediis Raioni',
     '49': 'Senakis Raioni',
     '50': 'Sighnaghis Raioni',
     '51': 'T\'bilisi',
     '52': 'T\'elavis Raioni',
     '53': 'T\'erjolis Raioni',
     '54': 'T\'et\'ritsqaros Raioni',
     '55': 'T\'ianet\'is Raioni',
     '56': 'Tqibuli',
     '57': 'Ts\'ageris Raioni',
     '58': 'Tsalenjikhis Raioni',
     '59': 'Tsalkis Raioni',
     '60': 'Tsqaltubo',
     '61': 'Vanis Raioni',
     '62': 'Zestap\'onis Raioni',
     '63': 'Zugdidi',
     '64': 'Zugdidis Raioni'
   },
   'GH': {
     '01': 'Greater Accra',
     '02': 'Ashanti',
     '03': 'Brong-Ahafo',
     '04': 'Central',
     '05': 'Eastern',
     '06': 'Northern',
     '08': 'Volta',
     '09': 'Western',
     '10': 'Upper East',
     '11': 'Upper West'
   },
   'GL': {
     '01': 'Nordgronland',
     '02': 'Ostgronland',
     '03': 'Vestgronland'
   },
   'GM': {
     '01': 'Banjul',
     '02': 'Lower River',
     '03': 'Central River',
     '04': 'Upper River',
     '05': 'Western',
     '07': 'North Bank'
   },
   'GN': {
     '01': 'Beyla',
     '02': 'Boffa',
     '03': 'Boke',
     '04': 'Conakry',
     '05': 'Dabola',
     '06': 'Dalaba',
     '07': 'Dinguiraye',
     '09': 'Faranah',
     '10': 'Forecariah',
     '11': 'Fria',
     '12': 'Gaoual',
     '13': 'Gueckedou',
     '15': 'Kerouane',
     '16': 'Kindia',
     '17': 'Kissidougou',
     '18': 'Koundara',
     '19': 'Kouroussa',
     '21': 'Macenta',
     '22': 'Mali',
     '23': 'Mamou',
     '25': 'Pita',
     '27': 'Telimele',
     '28': 'Tougue',
     '29': 'Yomou',
     '30': 'Coyah',
     '31': 'Dubreka',
     '32': 'Kankan',
     '33': 'Koubia',
     '34': 'Labe',
     '35': 'Lelouma',
     '36': 'Lola',
     '37': 'Mandiana',
     '38': 'Nzerekore',
     '39': 'Siguiri'
   },
   'GQ': {
     '03': 'Annobon',
     '04': 'Bioko Norte',
     '05': 'Bioko Sur',
     '06': 'Centro Sur',
     '07': 'Kie-Ntem',
     '08': 'Litoral',
     '09': 'Wele-Nzas'
   },
   'GR': {
     '01': 'Evros',
     '02': 'Rodhopi',
     '03': 'Xanthi',
     '04': 'Drama',
     '05': 'Serrai',
     '06': 'Kilkis',
     '07': 'Pella',
     '08': 'Florina',
     '09': 'Kastoria',
     '10': 'Grevena',
     '11': 'Kozani',
     '12': 'Imathia',
     '13': 'Thessaloniki',
     '14': 'Kavala',
     '15': 'Khalkidhiki',
     '16': 'Pieria',
     '17': 'Ioannina',
     '18': 'Thesprotia',
     '19': 'Preveza',
     '20': 'Arta',
     '21': 'Larisa',
     '22': 'Trikala',
     '23': 'Kardhitsa',
     '24': 'Magnisia',
     '25': 'Kerkira',
     '26': 'Levkas',
     '27': 'Kefallinia',
     '28': 'Zakinthos',
     '29': 'Fthiotis',
     '30': 'Evritania',
     '31': 'Aitolia kai Akarnania',
     '32': 'Fokis',
     '33': 'Voiotia',
     '34': 'Evvoia',
     '35': 'Attiki',
     '36': 'Argolis',
     '37': 'Korinthia',
     '38': 'Akhaia',
     '39': 'Ilia',
     '40': 'Messinia',
     '41': 'Arkadhia',
     '42': 'Lakonia',
     '43': 'Khania',
     '44': 'Rethimni',
     '45': 'Iraklion',
     '46': 'Lasithi',
     '47': 'Dhodhekanisos',
     '48': 'Samos',
     '49': 'Kikladhes',
     '50': 'Khios',
     '51': 'Lesvos'
   },
   'GT': {
     '01': 'Alta Verapaz',
     '02': 'Baja Verapaz',
     '03': 'Chimaltenango',
     '04': 'Chiquimula',
     '05': 'El Progreso',
     '06': 'Escuintla',
     '07': 'Guatemala',
     '08': 'Huehuetenango',
     '09': 'Izabal',
     '10': 'Jalapa',
     '11': 'Jutiapa',
     '12': 'Peten',
     '13': 'Quetzaltenango',
     '14': 'Quiche',
     '15': 'Retalhuleu',
     '16': 'Sacatepequez',
     '17': 'San Marcos',
     '18': 'Santa Rosa',
     '19': 'Solola',
     '20': 'Suchitepequez',
     '21': 'Totonicapan',
     '22': 'Zacapa'
   },
   'GW': {
     '01': 'Bafata',
     '02': 'Quinara',
     '04': 'Oio',
     '05': 'Bolama',
     '06': 'Cacheu',
     '07': 'Tombali',
     '10': 'Gabu',
     '11': 'Bissau',
     '12': 'Biombo'
   },
   'GY': {
     '10': 'Barima-Waini',
     '11': 'Cuyuni-Mazaruni',
     '12': 'Demerara-Mahaica',
     '13': 'East Berbice-Corentyne',
     '14': 'Essequibo Islands-West Demerara',
     '15': 'Mahaica-Berbice',
     '16': 'Pomeroon-Supenaam',
     '17': 'Potaro-Siparuni',
     '18': 'Upper Demerara-Berbice',
     '19': 'Upper Takutu-Upper Essequibo'
   },
   'HN': {
     '01': 'Atlantida',
     '02': 'Choluteca',
     '03': 'Colon',
     '04': 'Comayagua',
     '05': 'Copan',
     '06': 'Cortes',
     '07': 'El Paraiso',
     '08': 'Francisco Morazan',
     '09': 'Gracias a Dios',
     '10': 'Intibuca',
     '11': 'Islas de la Bahia',
     '12': 'La Paz',
     '13': 'Lempira',
     '14': 'Ocotepeque',
     '15': 'Olancho',
     '16': 'Santa Barbara',
     '17': 'Valle',
     '18': 'Yoro'
   },
   'HR': {
     '01': 'Bjelovarsko-Bilogorska',
     '02': 'Brodsko-Posavska',
     '03': 'Dubrovacko-Neretvanska',
     '04': 'Istarska',
     '05': 'Karlovacka',
     '06': 'Koprivnicko-Krizevacka',
     '07': 'Krapinsko-Zagorska',
     '08': 'Licko-Senjska',
     '09': 'Medimurska',
     '10': 'Osjecko-Baranjska',
     '11': 'Pozesko-Slavonska',
     '12': 'Primorsko-Goranska',
     '13': 'Sibensko-Kninska',
     '14': 'Sisacko-Moslavacka',
     '15': 'Splitsko-Dalmatinska',
     '16': 'Varazdinska',
     '17': 'Viroviticko-Podravska',
     '18': 'Vukovarsko-Srijemska',
     '19': 'Zadarska',
     '20': 'Zagrebacka',
     '21': 'Grad Zagreb'
   },
   'HT': {
     '03': 'Nord-Ouest',
     '06': 'Artibonite',
     '07': 'Centre',
     '09': 'Nord',
     '10': 'Nord-Est',
     '11': 'Ouest',
     '12': 'Sud',
     '13': 'Sud-Est',
     '14': 'Grand\' Anse',
     '15': 'Nippes'
   },
   'HU': {
     '01': 'Bacs-Kiskun',
     '02': 'Baranya',
     '03': 'Bekes',
     '04': 'Borsod-Abauj-Zemplen',
     '05': 'Budapest',
     '06': 'Csongrad',
     '07': 'Debrecen',
     '08': 'Fejer',
     '09': 'Gyor-Moson-Sopron',
     '10': 'Hajdu-Bihar',
     '11': 'Heves',
     '12': 'Komarom-Esztergom',
     '13': 'Miskolc',
     '14': 'Nograd',
     '15': 'Pecs',
     '16': 'Pest',
     '17': 'Somogy',
     '18': 'Szabolcs-Szatmar-Bereg',
     '19': 'Szeged',
     '20': 'Jasz-Nagykun-Szolnok',
     '21': 'Tolna',
     '22': 'Vas',
     '23': 'Veszprem',
     '24': 'Zala',
     '25': 'Gyor',
     '26': 'Bekescsaba',
     '27': 'Dunaujvaros',
     '28': 'Eger',
     '29': 'Hodmezovasarhely',
     '30': 'Kaposvar',
     '31': 'Kecskemet',
     '32': 'Nagykanizsa',
     '33': 'Nyiregyhaza',
     '34': 'Sopron',
     '35': 'Szekesfehervar',
     '36': 'Szolnok',
     '37': 'Szombathely',
     '38': 'Tatabanya',
     '39': 'Veszprem',
     '40': 'Zalaegerszeg',
     '41': 'Salgotarjan',
     '42': 'Szekszard',
     '43': 'Erd'
   },
   'ID': {
     '01': 'Aceh',
     '02': 'Bali',
     '03': 'Bengkulu',
     '04': 'Jakarta Raya',
     '05': 'Jambi',
     '07': 'Jawa Tengah',
     '08': 'Jawa Timur',
     '10': 'Yogyakarta',
     '11': 'Kalimantan Barat',
     '12': 'Kalimantan Selatan',
     '13': 'Kalimantan Tengah',
     '14': 'Kalimantan Timur',
     '15': 'Lampung',
     '17': 'Nusa Tenggara Barat',
     '18': 'Nusa Tenggara Timur',
     '21': 'Sulawesi Tengah',
     '22': 'Sulawesi Tenggara',
     '24': 'Sumatera Barat',
     '26': 'Sumatera Utara',
     '28': 'Maluku',
     '29': 'Maluku Utara',
     '30': 'Jawa Barat',
     '31': 'Sulawesi Utara',
     '32': 'Sumatera Selatan',
     '33': 'Banten',
     '34': 'Gorontalo',
     '35': 'Kepulauan Bangka Belitung',
     '36': 'Papua',
     '37': 'Riau',
     '38': 'Sulawesi Selatan',
     '39': 'Irian Jaya Barat',
     '40': 'Kepulauan Riau',
     '41': 'Sulawesi Barat'
   },
   'IE': {
     '01': 'Carlow',
     '02': 'Cavan',
     '03': 'Clare',
     '04': 'Cork',
     '06': 'Donegal',
     '07': 'Dublin',
     '10': 'Galway',
     '11': 'Kerry',
     '12': 'Kildare',
     '13': 'Kilkenny',
     '14': 'Leitrim',
     '15': 'Laois',
     '16': 'Limerick',
     '18': 'Longford',
     '19': 'Louth',
     '20': 'Mayo',
     '21': 'Meath',
     '22': 'Monaghan',
     '23': 'Offaly',
     '24': 'Roscommon',
     '25': 'Sligo',
     '26': 'Tipperary',
     '27': 'Waterford',
     '29': 'Westmeath',
     '30': 'Wexford',
     '31': 'Wicklow'
   },
   'IL': {
     '01': 'HaDarom',
     '02': 'HaMerkaz',
     '03': 'HaZafon',
     '04': 'Hefa',
     '05': 'Tel Aviv',
     '06': 'Yerushalayim'
   },
   'IN': {
     '01': 'Andaman and Nicobar Islands',
     '02': 'Andhra Pradesh',
     '03': 'Assam',
     '05': 'Chandigarh',
     '06': 'Dadra and Nagar Haveli',
     '07': 'Delhi',
     '09': 'Gujarat',
     '10': 'Haryana',
     '11': 'Himachal Pradesh',
     '12': 'Jammu and Kashmir',
     '13': 'Kerala',
     '14': 'Lakshadweep',
     '16': 'Maharashtra',
     '17': 'Manipur',
     '18': 'Meghalaya',
     '19': 'Karnataka',
     '20': 'Nagaland',
     '21': 'Orissa',
     '22': 'Puducherry',
     '23': 'Punjab',
     '24': 'Rajasthan',
     '25': 'Tamil Nadu',
     '26': 'Tripura',
     '28': 'West Bengal',
     '29': 'Sikkim',
     '30': 'Arunachal Pradesh',
     '31': 'Mizoram',
     '32': 'Daman and Diu',
     '33': 'Goa',
     '34': 'Bihar',
     '35': 'Madhya Pradesh',
     '36': 'Uttar Pradesh',
     '37': 'Chhattisgarh',
     '38': 'Jharkhand',
     '39': 'Uttarakhand'
   },
   'IQ': {
     '01': 'Al Anbar',
     '02': 'Al Basrah',
     '03': 'Al Muthanna',
     '04': 'Al Qadisiyah',
     '05': 'As Sulaymaniyah',
     '06': 'Babil',
     '07': 'Baghdad',
     '08': 'Dahuk',
     '09': 'Dhi Qar',
     '10': 'Diyala',
     '11': 'Arbil',
     '12': 'Karbala\'',
     '13': 'At Ta\'mim',
     '14': 'Maysan',
     '15': 'Ninawa',
     '16': 'Wasit',
     '17': 'An Najaf',
     '18': 'Salah ad Din'
   },
   'IR': {
     '01': 'Azarbayjan-e Bakhtari',
     '03': 'Chahar Mahall va Bakhtiari',
     '04': 'Sistan va Baluchestan',
     '05': 'Kohkiluyeh va Buyer Ahmadi',
     '07': 'Fars',
     '08': 'Gilan',
     '09': 'Hamadan',
     '10': 'Ilam',
     '11': 'Hormozgan',
     '12': 'Kerman',
     '13': 'Bakhtaran',
     '15': 'Khuzestan',
     '16': 'Kordestan',
     '17': 'Mazandaran',
     '18': 'Semnan Province',
     '19': 'Markazi',
     '21': 'Zanjan',
     '22': 'Bushehr',
     '23': 'Lorestan',
     '24': 'Markazi',
     '25': 'Semnan',
     '26': 'Tehran',
     '27': 'Zanjan',
     '28': 'Esfahan',
     '29': 'Kerman',
     '30': 'Khorasan',
     '31': 'Yazd',
     '32': 'Ardabil',
     '33': 'East Azarbaijan',
     '34': 'Markazi',
     '35': 'Mazandaran',
     '36': 'Zanjan',
     '37': 'Golestan',
     '38': 'Qazvin',
     '39': 'Qom',
     '40': 'Yazd',
     '41': 'Khorasan-e Janubi',
     '42': 'Khorasan-e Razavi',
     '43': 'Khorasan-e Shemali',
     '44': 'Alborz'
   },
   'IS': {
     '03': 'Arnessysla',
     '05': 'Austur-Hunavatnssysla',
     '06': 'Austur-Skaftafellssysla',
     '07': 'Borgarfjardarsysla',
     '09': 'Eyjafjardarsysla',
     '10': 'Gullbringusysla',
     '15': 'Kjosarsysla',
     '17': 'Myrasysla',
     '20': 'Nordur-Mulasysla',
     '21': 'Nordur-Tingeyjarsysla',
     '23': 'Rangarvallasysla',
     '28': 'Skagafjardarsysla',
     '29': 'Snafellsnes- og Hnappadalssysla',
     '30': 'Strandasysla',
     '31': 'Sudur-Mulasysla',
     '32': 'Sudur-Tingeyjarsysla',
     '34': 'Vestur-Bardastrandarsysla',
     '35': 'Vestur-Hunavatnssysla',
     '36': 'Vestur-Isafjardarsysla',
     '37': 'Vestur-Skaftafellssysla',
     '40': 'Norourland Eystra',
     '41': 'Norourland Vestra',
     '42': 'Suourland',
     '43': 'Suournes',
     '44': 'Vestfiroir',
     '45': 'Vesturland'
   },
   'IT': {
     '01': 'Abruzzi',
     '02': 'Basilicata',
     '03': 'Calabria',
     '04': 'Campania',
     '05': 'Emilia-Romagna',
     '06': 'Friuli-Venezia Giulia',
     '07': 'Lazio',
     '08': 'Liguria',
     '09': 'Lombardia',
     '10': 'Marche',
     '11': 'Molise',
     '12': 'Piemonte',
     '13': 'Puglia',
     '14': 'Sardegna',
     '15': 'Sicilia',
     '16': 'Toscana',
     '17': 'Trentino-Alto Adige',
     '18': 'Umbria',
     '19': 'Valle d\'Aosta',
     '20': 'Veneto'
   },
   'JM': {
     '01': 'Clarendon',
     '02': 'Hanover',
     '04': 'Manchester',
     '07': 'Portland',
     '08': 'Saint Andrew',
     '09': 'Saint Ann',
     '10': 'Saint Catherine',
     '11': 'Saint Elizabeth',
     '12': 'Saint James',
     '13': 'Saint Mary',
     '14': 'Saint Thomas',
     '15': 'Trelawny',
     '16': 'Westmoreland',
     '17': 'Kingston'
   },
   'JO': {
     '02': 'Al Balqa\'',
     '09': 'Al Karak',
     '12': 'At Tafilah',
     '15': 'Al Mafraq',
     '16': 'Amman',
     '17': 'Az Zaraqa',
     '18': 'Irbid',
     '19': 'Ma\'an',
     '20': 'Ajlun',
     '21': 'Al Aqabah',
     '22': 'Jarash',
     '23': 'Madaba'
   },
   'JP': {
     '01': 'Aichi',
     '02': 'Akita',
     '03': 'Aomori',
     '04': 'Chiba',
     '05': 'Ehime',
     '06': 'Fukui',
     '07': 'Fukuoka',
     '08': 'Fukushima',
     '09': 'Gifu',
     '10': 'Gumma',
     '11': 'Hiroshima',
     '12': 'Hokkaido',
     '13': 'Hyogo',
     '14': 'Ibaraki',
     '15': 'Ishikawa',
     '16': 'Iwate',
     '17': 'Kagawa',
     '18': 'Kagoshima',
     '19': 'Kanagawa',
     '20': 'Kochi',
     '21': 'Kumamoto',
     '22': 'Kyoto',
     '23': 'Mie',
     '24': 'Miyagi',
     '25': 'Miyazaki',
     '26': 'Nagano',
     '27': 'Nagasaki',
     '28': 'Nara',
     '29': 'Niigata',
     '30': 'Oita',
     '31': 'Okayama',
     '32': 'Osaka',
     '33': 'Saga',
     '34': 'Saitama',
     '35': 'Shiga',
     '36': 'Shimane',
     '37': 'Shizuoka',
     '38': 'Tochigi',
     '39': 'Tokushima',
     '40': 'Tokyo',
     '41': 'Tottori',
     '42': 'Toyama',
     '43': 'Wakayama',
     '44': 'Yamagata',
     '45': 'Yamaguchi',
     '46': 'Yamanashi',
     '47': 'Okinawa'
   },
   'KE': {
     '01': 'Central',
     '02': 'Coast',
     '03': 'Eastern',
     '05': 'Nairobi Area',
     '06': 'North-Eastern',
     '07': 'Nyanza',
     '08': 'Rift Valley',
     '09': 'Western'
   },
   'KG': {
     '01': 'Bishkek',
     '02': 'Chuy',
     '03': 'Jalal-Abad',
     '04': 'Naryn',
     '05': 'Osh',
     '06': 'Talas',
     '07': 'Ysyk-Kol',
     '08': 'Osh',
     '09': 'Batken'
   },
   'KH': {
     '01': 'Batdambang',
     '02': 'Kampong Cham',
     '03': 'Kampong Chhnang',
     '04': 'Kampong Speu',
     '05': 'Kampong Thum',
     '06': 'Kampot',
     '07': 'Kandal',
     '08': 'Koh Kong',
     '09': 'Kracheh',
     '10': 'Mondulkiri',
     '11': 'Phnum Penh',
     '12': 'Pursat',
     '13': 'Preah Vihear',
     '14': 'Prey Veng',
     '15': 'Ratanakiri Kiri',
     '16': 'Siem Reap',
     '17': 'Stung Treng',
     '18': 'Svay Rieng',
     '19': 'Takeo',
     '25': 'Banteay Meanchey',
     '29': 'Batdambang',
     '30': 'Pailin'
   },
   'KI': {
     '01': 'Gilbert Islands',
     '02': 'Line Islands',
     '03': 'Phoenix Islands'
   },
   'KM': {
     '01': 'Anjouan',
     '02': 'Grande Comore',
     '03': 'Moheli'
   },
   'KN': {
     '01': 'Christ Church Nichola Town',
     '02': 'Saint Anne Sandy Point',
     '03': 'Saint George Basseterre',
     '04': 'Saint George Gingerland',
     '05': 'Saint James Windward',
     '06': 'Saint John Capisterre',
     '07': 'Saint John Figtree',
     '08': 'Saint Mary Cayon',
     '09': 'Saint Paul Capisterre',
     '10': 'Saint Paul Charlestown',
     '11': 'Saint Peter Basseterre',
     '12': 'Saint Thomas Lowland',
     '13': 'Saint Thomas Middle Island',
     '15': 'Trinity Palmetto Point'
   },
   'KP': {
     '01': 'Chagang-do',
     '03': 'Hamgyong-namdo',
     '06': 'Hwanghae-namdo',
     '07': 'Hwanghae-bukto',
     '08': 'Kaesong-si',
     '09': 'Kangwon-do',
     '11': 'P\'yongan-bukto',
     '12': 'P\'yongyang-si',
     '13': 'Yanggang-do',
     '14': 'Namp\'o-si',
     '15': 'P\'yongan-namdo',
     '17': 'Hamgyong-bukto',
     '18': 'Najin Sonbong-si'
   },
   'KR': {
     '01': 'Cheju-do',
     '03': 'Cholla-bukto',
     '05': 'Ch\'ungch\'ong-bukto',
     '06': 'Kangwon-do',
     '10': 'Pusan-jikhalsi',
     '11': 'Seoul-t\'ukpyolsi',
     '12': 'Inch\'on-jikhalsi',
     '13': 'Kyonggi-do',
     '14': 'Kyongsang-bukto',
     '15': 'Taegu-jikhalsi',
     '16': 'Cholla-namdo',
     '17': 'Ch\'ungch\'ong-namdo',
     '18': 'Kwangju-jikhalsi',
     '19': 'Taejon-jikhalsi',
     '20': 'Kyongsang-namdo',
     '21': 'Ulsan-gwangyoksi'
   },
   'KW': {
     '01': 'Al Ahmadi',
     '02': 'Al Kuwayt',
     '05': 'Al Jahra',
     '07': 'Al Farwaniyah',
     '08': 'Hawalli',
     '09': 'Mubarak al Kabir'
   },
   'KY': {
     '01': 'Creek',
     '02': 'Eastern',
     '03': 'Midland',
     '04': 'South Town',
     '05': 'Spot Bay',
     '06': 'Stake Bay',
     '07': 'West End',
     '08': 'Western'
   },
   'KZ': {
     '01': 'Almaty',
     '02': 'Almaty City',
     '03': 'Aqmola',
     '04': 'Aqtobe',
     '05': 'Astana',
     '06': 'Atyrau',
     '07': 'West Kazakhstan',
     '08': 'Bayqonyr',
     '09': 'Mangghystau',
     '10': 'South Kazakhstan',
     '11': 'Pavlodar',
     '12': 'Qaraghandy',
     '13': 'Qostanay',
     '14': 'Qyzylorda',
     '15': 'East Kazakhstan',
     '16': 'North Kazakhstan',
     '17': 'Zhambyl'
   },
   'LA': {
     '01': 'Attapu',
     '02': 'Champasak',
     '03': 'Houaphan',
     '04': 'Khammouan',
     '05': 'Louang Namtha',
     '07': 'Oudomxai',
     '08': 'Phongsali',
     '09': 'Saravan',
     '10': 'Savannakhet',
     '11': 'Vientiane',
     '13': 'Xaignabouri',
     '14': 'Xiangkhoang',
     '17': 'Louangphrabang'
   },
   'LB': {
     '01': 'Beqaa',
     '02': 'Al Janub',
     '03': 'Liban-Nord',
     '04': 'Beyrouth',
     '05': 'Mont-Liban',
     '06': 'Liban-Sud',
     '07': 'Nabatiye',
     '08': 'Beqaa',
     '09': 'Liban-Nord',
     '10': 'Aakk,r',
     '11': 'Baalbek-Hermel'
   },
   'LC': {
     '01': 'Anse-la-Raye',
     '02': 'Dauphin',
     '03': 'Castries',
     '04': 'Choiseul',
     '05': 'Dennery',
     '06': 'Gros-Islet',
     '07': 'Laborie',
     '08': 'Micoud',
     '09': 'Soufriere',
     '10': 'Vieux-Fort',
     '11': 'Praslin'
   },
   'LI': {
     '01': 'Balzers',
     '02': 'Eschen',
     '03': 'Gamprin',
     '04': 'Mauren',
     '05': 'Planken',
     '06': 'Ruggell',
     '07': 'Schaan',
     '08': 'Schellenberg',
     '09': 'Triesen',
     '10': 'Triesenberg',
     '11': 'Vaduz',
     '21': 'Gbarpolu',
     '22': 'River Gee'
   },
   'LK': {
     '29': 'Central',
     '30': 'North Central',
     '32': 'North Western',
     '33': 'Sabaragamuwa',
     '34': 'Southern',
     '35': 'Uva',
     '36': 'Western',
     '37': 'Eastern',
     '38': 'Northern'
   },
   'LR': {
     '01': 'Bong',
     '04': 'Grand Cape Mount',
     '05': 'Lofa',
     '06': 'Maryland',
     '07': 'Monrovia',
     '09': 'Nimba',
     '10': 'Sino',
     '11': 'Grand Bassa',
     '12': 'Grand Cape Mount',
     '13': 'Maryland',
     '14': 'Montserrado',
     '17': 'Margibi',
     '18': 'River Cess',
     '19': 'Grand Gedeh',
     '20': 'Lofa',
     '21': 'Gbarpolu',
     '22': 'River Gee'
   },
   'LS': {
     '10': 'Berea',
     '11': 'Butha-Buthe',
     '12': 'Leribe',
     '13': 'Mafeteng',
     '14': 'Maseru',
     '15': 'Mohales Hoek',
     '16': 'Mokhotlong',
     '17': 'Qachas Nek',
     '18': 'Quthing',
     '19': 'Thaba-Tseka'
   },
   'LT': {
     '56': 'Alytaus Apskritis',
     '57': 'Kauno Apskritis',
     '58': 'Klaipedos Apskritis',
     '59': 'Marijampoles Apskritis',
     '60': 'Panevezio Apskritis',
     '61': 'Siauliu Apskritis',
     '62': 'Taurages Apskritis',
     '63': 'Telsiu Apskritis',
     '64': 'Utenos Apskritis',
     '65': 'Vilniaus Apskritis'
   },
   'LU': {
     '01': 'Diekirch',
     '02': 'Grevenmacher',
     '03': 'Luxembourg'
   },
   'LV': {
     '01': 'Aizkraukles',
     '02': 'Aluksnes',
     '03': 'Balvu',
     '04': 'Bauskas',
     '05': 'Cesu',
     '06': 'Daugavpils',
     '07': 'Daugavpils',
     '08': 'Dobeles',
     '09': 'Gulbenes',
     '10': 'Jekabpils',
     '11': 'Jelgava',
     '12': 'Jelgavas',
     '13': 'Jurmala',
     '14': 'Kraslavas',
     '15': 'Kuldigas',
     '16': 'Liepaja',
     '17': 'Liepajas',
     '18': 'Limbazu',
     '19': 'Ludzas',
     '20': 'Madonas',
     '21': 'Ogres',
     '22': 'Preilu',
     '23': 'Rezekne',
     '24': 'Rezeknes',
     '25': 'Riga',
     '26': 'Rigas',
     '27': 'Saldus',
     '28': 'Talsu',
     '29': 'Tukuma',
     '30': 'Valkas',
     '31': 'Valmieras',
     '32': 'Ventspils',
     '33': 'Ventspils'
   },
   'LY': {
     '03': 'Al Aziziyah',
     '05': 'Al Jufrah',
     '08': 'Al Kufrah',
     '13': 'Ash Shati\'',
     '30': 'Murzuq',
     '34': 'Sabha',
     '41': 'Tarhunah',
     '42': 'Tubruq',
     '45': 'Zlitan',
     '47': 'Ajdabiya',
     '48': 'Al Fatih',
     '49': 'Al Jabal al Akhdar',
     '50': 'Al Khums',
     '51': 'An Nuqat al Khams',
     '52': 'Awbari',
     '53': 'Az Zawiyah',
     '54': 'Banghazi',
     '55': 'Darnah',
     '56': 'Ghadamis',
     '57': 'Gharyan',
     '58': 'Misratah',
     '59': 'Sawfajjin',
     '60': 'Surt',
     '61': 'Tarabulus',
     '62': 'Yafran'
   }

}
