/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kdgregory_example_bytebuffer_jni_SharedMem */

#ifndef _Included_com_kdgregory_example_bytebuffer_jni_SharedMem
#define _Included_com_kdgregory_example_bytebuffer_jni_SharedMem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kdgregory_example_bytebuffer_jni_SharedMem
 * Method:    jniInit
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_kdgregory_example_bytebuffer_jni_SharedMem_jniInit
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_kdgregory_example_bytebuffer_jni_SharedMem
 * Method:    jniTerm
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kdgregory_example_bytebuffer_jni_SharedMem_jniTerm
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
