/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class aos_jni_JavaJni */

#ifndef _Included_aos_jni_JavaJni
#define _Included_aos_jni_JavaJni
#ifdef __cplusplus
extern "C" {
#endif
#undef aos_jni_JavaJni_X
#define aos_jni_JavaJni_X 100000000LL
#undef aos_jni_JavaJni_Y
#define aos_jni_JavaJni_Y 50LL
/*
 * Class:     aos_jni_JavaJni
 * Method:    zerocpp
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_aos_jni_JavaJni_zerocpp
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
